// playgrounds/solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import { retrieveLaunchParams } from '@openweb3-apps/sdk-solid';

import './index.css';

import { Root } from '@/components/Root.js';
import { init } from '@/init.js';

// Uncomment this import in case, you would like to develop the application even outside
// the Openweb3 application, just in your browser.
// import './mockEnv.ts';

const root = document.getElementById('root');

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?',
  );
}

// Configure all application dependencies.
init(retrieveLaunchParams().startParam === 'debug');

render(() => (<Root/>), root!);

// playgrounds/react/src/index.tsx
import ReactDOM from 'react-dom/client';
import { StrictMode } from 'react';
import { retrieveLaunchParams } from '@openweb3-apps/sdk-react';

import { Root } from '@/components/Root';
import { init } from '@/init.ts';

import '@openweb3-apps/openweb3-ui/dist/styles.css';
import './index.css';

// Mock the environment in case, we are outside Openweb3.
import './mockEnv.ts';

// Configure all application dependencies.
init(retrieveLaunchParams().startParam === 'debug');

ReactDOM.createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <Root/>
  </StrictMode>,
);
