// playgrounds/vue/src/pages/ThemeParamsPage.vue
<script setup lang="ts">
import { computed } from 'vue';
import { themeParams, useSignal } from '@openweb3-apps/sdk-vue';
import UiDisplayData, { type DisplayDataRow } from '@/components/UiDisplayData.vue';
import UiLink from '@/components/UiLink.vue';
import UiPage from '@/components/UiPage.vue';

const tp = useSignal(themeParams.state);

const rows = computed<DisplayDataRow[]>(() => Object
  .entries(tp.value)
  .map(([title, value]) => ({
    title: title
      .replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)
      .replace(/background/, 'bg'),
    value,
  })));
</script>

<template>
  <UiPage title="Theme Params">
    <template #disclaimer>
      This page displays current <UiLink to="https://docs.openweb3-mini-apps.com/platform/theming">theme params
      </UiLink>.
    </template>
    <UiDisplayData :rows />
  </UiPage>
</template>

// playgrounds/react/src/pages/ThemeParamsPage.tsx
import { themeParams, useSignal } from '@openweb3-apps/sdk-react';
import type { FC } from 'react';
import { List } from '@openweb3-apps/openweb3-ui';

import { DisplayData } from '@/components/DisplayData/DisplayData.tsx';
import { Page } from '@/components/Page.tsx';

export const ThemeParamsPage: FC = () => {
  const tp = useSignal(themeParams.state);

  return (
    <Page>
      <List>
        <DisplayData
          rows={
            Object
              .entries(tp)
              .map(([title, value]) => ({
                title: title
                  .replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)
                  .replace(/background/, 'bg'),
                value,
              }))
          }
        />
      </List>
    </Page>
  );
};
