// playgrounds/solid/src/pages/LaunchParamsPage.tsx
import { useLaunchParams } from '@openweb3-apps/sdk-solid';
import type { Component } from 'solid-js';

import { DisplayData } from '@/components/DisplayData/DisplayData.js';
import { Link } from '@/components/Link/Link.js';
import { Page } from '@/components/Page/Page.js';

export const LaunchParamsPage: Component = () => {
  const lp = useLaunchParams();

  return (
    <Page
      title="Launch Params"
      disclaimer={(
        <>
          This page displays application
          {' '}
          <Link href="https://docs.openweb3-mini-apps.com/platform/launch-parameters">
            launch parameters
          </Link>
          .
        </>
      )}
    >
      <DisplayData
        rows={[
          { title: 'tgWebAppPlatform', value: lp.platform },
          { title: 'tgWebAppShowSettings', value: lp.showSettings },
          { title: 'tgWebAppVersion', value: lp.version },
          { title: 'tgWebAppBotInline', value: lp.botInline },
          { title: 'tgWebAppStartParam', value: lp.startParam },
          { title: 'tgWebAppData', value: <Link href="/init-data">View</Link> },
          { title: 'tgWebAppThemeParams', value: <Link href="/theme-params">View</Link> },
        ]}
      />
    </Page>
  );
};

// playgrounds/vue/src/pages/LaunchParamsPage.vue
<script setup lang="ts">
import { h } from 'vue';
import { useLaunchParams } from '@openweb3-apps/sdk-vue';
import UiLink from '@/components/UiLink.vue';
import UiPage from '@/components/UiPage.vue';
import UiDisplayData, { type DisplayDataRow } from '@/components/UiDisplayData.vue';

const lp = useLaunchParams();

const rows: DisplayDataRow[] = [
  { title: 'tgWebAppPlatform', value: lp.platform },
  { title: 'tgWebAppShowSettings', value: lp.showSettings },
  { title: 'tgWebAppVersion', value: lp.version },
  { title: 'tgWebAppBotInline', value: lp.botInline },
  { title: 'tgWebAppStartParam', value: lp.startParam },
  { title: 'tgWebAppData', value: { render: () => h(UiLink, { to: { name: 'init-data' } }, { default: () => 'View' }) } },
  { title: 'tgWebAppThemeParams', value: { render: () => h(UiLink, { to: { name: 'theme-params' } }, { default: () => 'View' }) } },
];
</script>

<template>
  <UiPage title="Launch Params">
    <template #disclaimer>
      This page displays application <UiLink to="https://docs.openweb3-mini-apps.com/platform/launch-parameters">
        launch params</UiLink>.
    </template>
    <UiDisplayData :rows />
  </UiPage>
</template>
